/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as ScoreEntryHoleRouteImport } from './routes/score-entry-hole'
import { Route as ScoreEntryRouteImport } from './routes/score-entry'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as OddsRouteImport } from './routes/odds'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as BallDrawRouteImport } from './routes/ball-draw'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StandingsHistoryRouteImport } from './routes/standings_.history'
import { Route as RoundRoundIdRouteImport } from './routes/round.$roundId'
import { Route as PairingsRoundIdRouteImport } from './routes/pairings.$roundId'
import { Route as AdminSeasonRouteImport } from './routes/admin/season'
import { Route as AdminScoreCorrectionsRouteImport } from './routes/admin/score-corrections'
import { Route as AdminRoundsRouteImport } from './routes/admin/rounds'
import { Route as AdminRosterRouteImport } from './routes/admin/roster'
import { Route as AdminLoginRouteImport } from './routes/admin/login'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreEntryHoleRoute = ScoreEntryHoleRouteImport.update({
  id: '/score-entry-hole',
  path: '/score-entry-hole',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreEntryRoute = ScoreEntryRouteImport.update({
  id: '/score-entry',
  path: '/score-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const OddsRoute = OddsRouteImport.update({
  id: '/odds',
  path: '/odds',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const BallDrawRoute = BallDrawRouteImport.update({
  id: '/ball-draw',
  path: '/ball-draw',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StandingsHistoryRoute = StandingsHistoryRouteImport.update({
  id: '/standings_/history',
  path: '/standings/history',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundRoundIdRoute = RoundRoundIdRouteImport.update({
  id: '/round/$roundId',
  path: '/round/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingsRoundIdRoute = PairingsRoundIdRouteImport.update({
  id: '/pairings/$roundId',
  path: '/pairings/$roundId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeasonRoute = AdminSeasonRouteImport.update({
  id: '/season',
  path: '/season',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScoreCorrectionsRoute = AdminScoreCorrectionsRouteImport.update({
  id: '/score-corrections',
  path: '/score-corrections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoundsRoute = AdminRoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRosterRoute = AdminRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/ball-draw': typeof BallDrawRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/odds': typeof OddsRoute
  '/practice': typeof PracticeRoute
  '/score-entry': typeof ScoreEntryRoute
  '/score-entry-hole': typeof ScoreEntryHoleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/score-corrections': typeof AdminScoreCorrectionsRoute
  '/admin/season': typeof AdminSeasonRoute
  '/pairings/$roundId': typeof PairingsRoundIdRoute
  '/round/$roundId': typeof RoundRoundIdRoute
  '/standings/history': typeof StandingsHistoryRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/ball-draw': typeof BallDrawRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/odds': typeof OddsRoute
  '/practice': typeof PracticeRoute
  '/score-entry': typeof ScoreEntryRoute
  '/score-entry-hole': typeof ScoreEntryHoleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/score-corrections': typeof AdminScoreCorrectionsRoute
  '/admin/season': typeof AdminSeasonRoute
  '/pairings/$roundId': typeof PairingsRoundIdRoute
  '/round/$roundId': typeof RoundRoundIdRoute
  '/standings/history': typeof StandingsHistoryRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/ball-draw': typeof BallDrawRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/gallery': typeof GalleryRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/odds': typeof OddsRoute
  '/practice': typeof PracticeRoute
  '/score-entry': typeof ScoreEntryRoute
  '/score-entry-hole': typeof ScoreEntryHoleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roster': typeof AdminRosterRoute
  '/admin/rounds': typeof AdminRoundsRoute
  '/admin/score-corrections': typeof AdminScoreCorrectionsRoute
  '/admin/season': typeof AdminSeasonRoute
  '/pairings/$roundId': typeof PairingsRoundIdRoute
  '/round/$roundId': typeof RoundRoundIdRoute
  '/standings_/history': typeof StandingsHistoryRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attendance'
    | '/ball-draw'
    | '/cheatsheet'
    | '/gallery'
    | '/guide'
    | '/help'
    | '/odds'
    | '/practice'
    | '/score-entry'
    | '/score-entry-hole'
    | '/standings'
    | '/stats'
    | '/admin/login'
    | '/admin/roster'
    | '/admin/rounds'
    | '/admin/score-corrections'
    | '/admin/season'
    | '/pairings/$roundId'
    | '/round/$roundId'
    | '/standings/history'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/ball-draw'
    | '/cheatsheet'
    | '/gallery'
    | '/guide'
    | '/help'
    | '/odds'
    | '/practice'
    | '/score-entry'
    | '/score-entry-hole'
    | '/standings'
    | '/stats'
    | '/admin/login'
    | '/admin/roster'
    | '/admin/rounds'
    | '/admin/score-corrections'
    | '/admin/season'
    | '/pairings/$roundId'
    | '/round/$roundId'
    | '/standings/history'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attendance'
    | '/ball-draw'
    | '/cheatsheet'
    | '/gallery'
    | '/guide'
    | '/help'
    | '/odds'
    | '/practice'
    | '/score-entry'
    | '/score-entry-hole'
    | '/standings'
    | '/stats'
    | '/admin/login'
    | '/admin/roster'
    | '/admin/rounds'
    | '/admin/score-corrections'
    | '/admin/season'
    | '/pairings/$roundId'
    | '/round/$roundId'
    | '/standings_/history'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  BallDrawRoute: typeof BallDrawRoute
  CheatsheetRoute: typeof CheatsheetRoute
  GalleryRoute: typeof GalleryRoute
  GuideRoute: typeof GuideRoute
  HelpRoute: typeof HelpRoute
  OddsRoute: typeof OddsRoute
  PracticeRoute: typeof PracticeRoute
  ScoreEntryRoute: typeof ScoreEntryRoute
  ScoreEntryHoleRoute: typeof ScoreEntryHoleRoute
  StandingsRoute: typeof StandingsRoute
  StatsRoute: typeof StatsRoute
  PairingsRoundIdRoute: typeof PairingsRoundIdRoute
  RoundRoundIdRoute: typeof RoundRoundIdRoute
  StandingsHistoryRoute: typeof StandingsHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-entry-hole': {
      id: '/score-entry-hole'
      path: '/score-entry-hole'
      fullPath: '/score-entry-hole'
      preLoaderRoute: typeof ScoreEntryHoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-entry': {
      id: '/score-entry'
      path: '/score-entry'
      fullPath: '/score-entry'
      preLoaderRoute: typeof ScoreEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/odds': {
      id: '/odds'
      path: '/odds'
      fullPath: '/odds'
      preLoaderRoute: typeof OddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ball-draw': {
      id: '/ball-draw'
      path: '/ball-draw'
      fullPath: '/ball-draw'
      preLoaderRoute: typeof BallDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/standings_/history': {
      id: '/standings_/history'
      path: '/standings/history'
      fullPath: '/standings/history'
      preLoaderRoute: typeof StandingsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/round/$roundId': {
      id: '/round/$roundId'
      path: '/round/$roundId'
      fullPath: '/round/$roundId'
      preLoaderRoute: typeof RoundRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairings/$roundId': {
      id: '/pairings/$roundId'
      path: '/pairings/$roundId'
      fullPath: '/pairings/$roundId'
      preLoaderRoute: typeof PairingsRoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/season': {
      id: '/admin/season'
      path: '/season'
      fullPath: '/admin/season'
      preLoaderRoute: typeof AdminSeasonRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/score-corrections': {
      id: '/admin/score-corrections'
      path: '/score-corrections'
      fullPath: '/admin/score-corrections'
      preLoaderRoute: typeof AdminScoreCorrectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rounds': {
      id: '/admin/rounds'
      path: '/rounds'
      fullPath: '/admin/rounds'
      preLoaderRoute: typeof AdminRoundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roster': {
      id: '/admin/roster'
      path: '/roster'
      fullPath: '/admin/roster'
      preLoaderRoute: typeof AdminRosterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRosterRoute: typeof AdminRosterRoute
  AdminRoundsRoute: typeof AdminRoundsRoute
  AdminScoreCorrectionsRoute: typeof AdminScoreCorrectionsRoute
  AdminSeasonRoute: typeof AdminSeasonRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminRosterRoute: AdminRosterRoute,
  AdminRoundsRoute: AdminRoundsRoute,
  AdminScoreCorrectionsRoute: AdminScoreCorrectionsRoute,
  AdminSeasonRoute: AdminSeasonRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  BallDrawRoute: BallDrawRoute,
  CheatsheetRoute: CheatsheetRoute,
  GalleryRoute: GalleryRoute,
  GuideRoute: GuideRoute,
  HelpRoute: HelpRoute,
  OddsRoute: OddsRoute,
  PracticeRoute: PracticeRoute,
  ScoreEntryRoute: ScoreEntryRoute,
  ScoreEntryHoleRoute: ScoreEntryHoleRoute,
  StandingsRoute: StandingsRoute,
  StatsRoute: StatsRoute,
  PairingsRoundIdRoute: PairingsRoundIdRoute,
  RoundRoundIdRoute: RoundRoundIdRoute,
  StandingsHistoryRoute: StandingsHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
