/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MeRouteImport } from './routes/me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthDeclinedRouteImport } from './routes/auth.declined'
import { Route as AuthConflictRouteImport } from './routes/auth.conflict'
import { Route as EventsEventIdIndexRouteImport } from './routes/events.$eventId.index'
import { Route as RoundsRoundIdScoreEntryRouteImport } from './routes/rounds.$roundId.score-entry'
import { Route as EventsEventIdSettleUpRouteImport } from './routes/events.$eventId.settle-up'
import { Route as EventsEventIdScheduleRouteImport } from './routes/events.$eventId.schedule'
import { Route as EventsEventIdMoneyRouteImport } from './routes/events.$eventId.money'
import { Route as EventsEventIdLeaderboardRouteImport } from './routes/events.$eventId.leaderboard'
import { Route as EventsEventIdGalleryRouteImport } from './routes/events.$eventId.gallery'
import { Route as EventsEventIdBetsRouteImport } from './routes/events.$eventId.bets'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminCoursesUploadRouteImport } from './routes/admin.courses.upload'
import { Route as AdminCoursesNewRouteImport } from './routes/admin.courses.new'
import { Route as AdminEventsEventIdIndexRouteImport } from './routes/admin.events.$eventId.index'
import { Route as EventsEventIdCoursesCourseIdRouteImport } from './routes/events.$eventId.courses.$courseId'
import { Route as AdminRuleSetsIdEditRouteImport } from './routes/admin.rule-sets.$id.edit'
import { Route as AdminGroupsGroupIdEditRouteImport } from './routes/admin.groups.$groupId.edit'
import { Route as AdminEventsEventIdStartRoundRouteImport } from './routes/admin.events.$eventId.start-round'
import { Route as AdminEventsEventIdPairingsRouteImport } from './routes/admin.events.$eventId.pairings'
import { Route as AdminEventRoundsEventRoundIdSubGamesRouteImport } from './routes/admin.event-rounds.$eventRoundId.sub-games'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeclinedRoute = AuthDeclinedRouteImport.update({
  id: '/auth/declined',
  path: '/auth/declined',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConflictRoute = AuthConflictRouteImport.update({
  id: '/auth/conflict',
  path: '/auth/conflict',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsRoundIdScoreEntryRoute = RoundsRoundIdScoreEntryRouteImport.update({
  id: '/rounds/$roundId/score-entry',
  path: '/rounds/$roundId/score-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdSettleUpRoute = EventsEventIdSettleUpRouteImport.update({
  id: '/events/$eventId/settle-up',
  path: '/events/$eventId/settle-up',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdScheduleRoute = EventsEventIdScheduleRouteImport.update({
  id: '/events/$eventId/schedule',
  path: '/events/$eventId/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdMoneyRoute = EventsEventIdMoneyRouteImport.update({
  id: '/events/$eventId/money',
  path: '/events/$eventId/money',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdLeaderboardRoute =
  EventsEventIdLeaderboardRouteImport.update({
    id: '/events/$eventId/leaderboard',
    path: '/events/$eventId/leaderboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsEventIdGalleryRoute = EventsEventIdGalleryRouteImport.update({
  id: '/events/$eventId/gallery',
  path: '/events/$eventId/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdBetsRoute = EventsEventIdBetsRouteImport.update({
  id: '/events/$eventId/bets',
  path: '/events/$eventId/bets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/admin/events/new',
  path: '/admin/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesUploadRoute = AdminCoursesUploadRouteImport.update({
  id: '/admin/courses/upload',
  path: '/admin/courses/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/admin/courses/new',
  path: '/admin/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdIndexRoute = AdminEventsEventIdIndexRouteImport.update({
  id: '/admin/events/$eventId/',
  path: '/admin/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdCoursesCourseIdRoute =
  EventsEventIdCoursesCourseIdRouteImport.update({
    id: '/events/$eventId/courses/$courseId',
    path: '/events/$eventId/courses/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRuleSetsIdEditRoute = AdminRuleSetsIdEditRouteImport.update({
  id: '/admin/rule-sets/$id/edit',
  path: '/admin/rule-sets/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGroupsGroupIdEditRoute = AdminGroupsGroupIdEditRouteImport.update({
  id: '/admin/groups/$groupId/edit',
  path: '/admin/groups/$groupId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventIdStartRoundRoute =
  AdminEventsEventIdStartRoundRouteImport.update({
    id: '/admin/events/$eventId/start-round',
    path: '/admin/events/$eventId/start-round',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventsEventIdPairingsRoute =
  AdminEventsEventIdPairingsRouteImport.update({
    id: '/admin/events/$eventId/pairings',
    path: '/admin/events/$eventId/pairings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEventRoundsEventRoundIdSubGamesRoute =
  AdminEventRoundsEventRoundIdSubGamesRouteImport.update({
    id: '/admin/event-rounds/$eventRoundId/sub-games',
    path: '/admin/event-rounds/$eventRoundId/sub-games',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/profile': typeof ProfileRoute
  '/auth/conflict': typeof AuthConflictRoute
  '/auth/declined': typeof AuthDeclinedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/upload': typeof AdminCoursesUploadRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/events/$eventId/bets': typeof EventsEventIdBetsRoute
  '/events/$eventId/gallery': typeof EventsEventIdGalleryRoute
  '/events/$eventId/leaderboard': typeof EventsEventIdLeaderboardRoute
  '/events/$eventId/money': typeof EventsEventIdMoneyRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/settle-up': typeof EventsEventIdSettleUpRoute
  '/rounds/$roundId/score-entry': typeof RoundsRoundIdScoreEntryRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/admin/event-rounds/$eventRoundId/sub-games': typeof AdminEventRoundsEventRoundIdSubGamesRoute
  '/admin/events/$eventId/pairings': typeof AdminEventsEventIdPairingsRoute
  '/admin/events/$eventId/start-round': typeof AdminEventsEventIdStartRoundRoute
  '/admin/groups/$groupId/edit': typeof AdminGroupsGroupIdEditRoute
  '/admin/rule-sets/$id/edit': typeof AdminRuleSetsIdEditRoute
  '/events/$eventId/courses/$courseId': typeof EventsEventIdCoursesCourseIdRoute
  '/admin/events/$eventId/': typeof AdminEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/profile': typeof ProfileRoute
  '/auth/conflict': typeof AuthConflictRoute
  '/auth/declined': typeof AuthDeclinedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/upload': typeof AdminCoursesUploadRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/events/$eventId/bets': typeof EventsEventIdBetsRoute
  '/events/$eventId/gallery': typeof EventsEventIdGalleryRoute
  '/events/$eventId/leaderboard': typeof EventsEventIdLeaderboardRoute
  '/events/$eventId/money': typeof EventsEventIdMoneyRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/settle-up': typeof EventsEventIdSettleUpRoute
  '/rounds/$roundId/score-entry': typeof RoundsRoundIdScoreEntryRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/admin/event-rounds/$eventRoundId/sub-games': typeof AdminEventRoundsEventRoundIdSubGamesRoute
  '/admin/events/$eventId/pairings': typeof AdminEventsEventIdPairingsRoute
  '/admin/events/$eventId/start-round': typeof AdminEventsEventIdStartRoundRoute
  '/admin/groups/$groupId/edit': typeof AdminGroupsGroupIdEditRoute
  '/admin/rule-sets/$id/edit': typeof AdminRuleSetsIdEditRoute
  '/events/$eventId/courses/$courseId': typeof EventsEventIdCoursesCourseIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/me': typeof MeRoute
  '/profile': typeof ProfileRoute
  '/auth/conflict': typeof AuthConflictRoute
  '/auth/declined': typeof AuthDeclinedRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/upload': typeof AdminCoursesUploadRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/events/$eventId/bets': typeof EventsEventIdBetsRoute
  '/events/$eventId/gallery': typeof EventsEventIdGalleryRoute
  '/events/$eventId/leaderboard': typeof EventsEventIdLeaderboardRoute
  '/events/$eventId/money': typeof EventsEventIdMoneyRoute
  '/events/$eventId/schedule': typeof EventsEventIdScheduleRoute
  '/events/$eventId/settle-up': typeof EventsEventIdSettleUpRoute
  '/rounds/$roundId/score-entry': typeof RoundsRoundIdScoreEntryRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/admin/event-rounds/$eventRoundId/sub-games': typeof AdminEventRoundsEventRoundIdSubGamesRoute
  '/admin/events/$eventId/pairings': typeof AdminEventsEventIdPairingsRoute
  '/admin/events/$eventId/start-round': typeof AdminEventsEventIdStartRoundRoute
  '/admin/groups/$groupId/edit': typeof AdminGroupsGroupIdEditRoute
  '/admin/rule-sets/$id/edit': typeof AdminRuleSetsIdEditRoute
  '/events/$eventId/courses/$courseId': typeof EventsEventIdCoursesCourseIdRoute
  '/admin/events/$eventId/': typeof AdminEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/me'
    | '/profile'
    | '/auth/conflict'
    | '/auth/declined'
    | '/invite/$token'
    | '/admin/courses/new'
    | '/admin/courses/upload'
    | '/admin/events/new'
    | '/events/$eventId/bets'
    | '/events/$eventId/gallery'
    | '/events/$eventId/leaderboard'
    | '/events/$eventId/money'
    | '/events/$eventId/schedule'
    | '/events/$eventId/settle-up'
    | '/rounds/$roundId/score-entry'
    | '/events/$eventId/'
    | '/admin/event-rounds/$eventRoundId/sub-games'
    | '/admin/events/$eventId/pairings'
    | '/admin/events/$eventId/start-round'
    | '/admin/groups/$groupId/edit'
    | '/admin/rule-sets/$id/edit'
    | '/events/$eventId/courses/$courseId'
    | '/admin/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/me'
    | '/profile'
    | '/auth/conflict'
    | '/auth/declined'
    | '/invite/$token'
    | '/admin/courses/new'
    | '/admin/courses/upload'
    | '/admin/events/new'
    | '/events/$eventId/bets'
    | '/events/$eventId/gallery'
    | '/events/$eventId/leaderboard'
    | '/events/$eventId/money'
    | '/events/$eventId/schedule'
    | '/events/$eventId/settle-up'
    | '/rounds/$roundId/score-entry'
    | '/events/$eventId'
    | '/admin/event-rounds/$eventRoundId/sub-games'
    | '/admin/events/$eventId/pairings'
    | '/admin/events/$eventId/start-round'
    | '/admin/groups/$groupId/edit'
    | '/admin/rule-sets/$id/edit'
    | '/events/$eventId/courses/$courseId'
    | '/admin/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/me'
    | '/profile'
    | '/auth/conflict'
    | '/auth/declined'
    | '/invite/$token'
    | '/admin/courses/new'
    | '/admin/courses/upload'
    | '/admin/events/new'
    | '/events/$eventId/bets'
    | '/events/$eventId/gallery'
    | '/events/$eventId/leaderboard'
    | '/events/$eventId/money'
    | '/events/$eventId/schedule'
    | '/events/$eventId/settle-up'
    | '/rounds/$roundId/score-entry'
    | '/events/$eventId/'
    | '/admin/event-rounds/$eventRoundId/sub-games'
    | '/admin/events/$eventId/pairings'
    | '/admin/events/$eventId/start-round'
    | '/admin/groups/$groupId/edit'
    | '/admin/rule-sets/$id/edit'
    | '/events/$eventId/courses/$courseId'
    | '/admin/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeRoute: typeof MeRoute
  ProfileRoute: typeof ProfileRoute
  AuthConflictRoute: typeof AuthConflictRoute
  AuthDeclinedRoute: typeof AuthDeclinedRoute
  InviteTokenRoute: typeof InviteTokenRoute
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminCoursesUploadRoute: typeof AdminCoursesUploadRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  EventsEventIdBetsRoute: typeof EventsEventIdBetsRoute
  EventsEventIdGalleryRoute: typeof EventsEventIdGalleryRoute
  EventsEventIdLeaderboardRoute: typeof EventsEventIdLeaderboardRoute
  EventsEventIdMoneyRoute: typeof EventsEventIdMoneyRoute
  EventsEventIdScheduleRoute: typeof EventsEventIdScheduleRoute
  EventsEventIdSettleUpRoute: typeof EventsEventIdSettleUpRoute
  RoundsRoundIdScoreEntryRoute: typeof RoundsRoundIdScoreEntryRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
  AdminEventRoundsEventRoundIdSubGamesRoute: typeof AdminEventRoundsEventRoundIdSubGamesRoute
  AdminEventsEventIdPairingsRoute: typeof AdminEventsEventIdPairingsRoute
  AdminEventsEventIdStartRoundRoute: typeof AdminEventsEventIdStartRoundRoute
  AdminGroupsGroupIdEditRoute: typeof AdminGroupsGroupIdEditRoute
  AdminRuleSetsIdEditRoute: typeof AdminRuleSetsIdEditRoute
  EventsEventIdCoursesCourseIdRoute: typeof EventsEventIdCoursesCourseIdRoute
  AdminEventsEventIdIndexRoute: typeof AdminEventsEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/declined': {
      id: '/auth/declined'
      path: '/auth/declined'
      fullPath: '/auth/declined'
      preLoaderRoute: typeof AuthDeclinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/conflict': {
      id: '/auth/conflict'
      path: '/auth/conflict'
      fullPath: '/auth/conflict'
      preLoaderRoute: typeof AuthConflictRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds/$roundId/score-entry': {
      id: '/rounds/$roundId/score-entry'
      path: '/rounds/$roundId/score-entry'
      fullPath: '/rounds/$roundId/score-entry'
      preLoaderRoute: typeof RoundsRoundIdScoreEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/settle-up': {
      id: '/events/$eventId/settle-up'
      path: '/events/$eventId/settle-up'
      fullPath: '/events/$eventId/settle-up'
      preLoaderRoute: typeof EventsEventIdSettleUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/schedule': {
      id: '/events/$eventId/schedule'
      path: '/events/$eventId/schedule'
      fullPath: '/events/$eventId/schedule'
      preLoaderRoute: typeof EventsEventIdScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/money': {
      id: '/events/$eventId/money'
      path: '/events/$eventId/money'
      fullPath: '/events/$eventId/money'
      preLoaderRoute: typeof EventsEventIdMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/leaderboard': {
      id: '/events/$eventId/leaderboard'
      path: '/events/$eventId/leaderboard'
      fullPath: '/events/$eventId/leaderboard'
      preLoaderRoute: typeof EventsEventIdLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/gallery': {
      id: '/events/$eventId/gallery'
      path: '/events/$eventId/gallery'
      fullPath: '/events/$eventId/gallery'
      preLoaderRoute: typeof EventsEventIdGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/bets': {
      id: '/events/$eventId/bets'
      path: '/events/$eventId/bets'
      fullPath: '/events/$eventId/bets'
      preLoaderRoute: typeof EventsEventIdBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/admin/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/upload': {
      id: '/admin/courses/upload'
      path: '/admin/courses/upload'
      fullPath: '/admin/courses/upload'
      preLoaderRoute: typeof AdminCoursesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/admin/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/': {
      id: '/admin/events/$eventId/'
      path: '/admin/events/$eventId'
      fullPath: '/admin/events/$eventId/'
      preLoaderRoute: typeof AdminEventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId/courses/$courseId': {
      id: '/events/$eventId/courses/$courseId'
      path: '/events/$eventId/courses/$courseId'
      fullPath: '/events/$eventId/courses/$courseId'
      preLoaderRoute: typeof EventsEventIdCoursesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rule-sets/$id/edit': {
      id: '/admin/rule-sets/$id/edit'
      path: '/admin/rule-sets/$id/edit'
      fullPath: '/admin/rule-sets/$id/edit'
      preLoaderRoute: typeof AdminRuleSetsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/groups/$groupId/edit': {
      id: '/admin/groups/$groupId/edit'
      path: '/admin/groups/$groupId/edit'
      fullPath: '/admin/groups/$groupId/edit'
      preLoaderRoute: typeof AdminGroupsGroupIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/start-round': {
      id: '/admin/events/$eventId/start-round'
      path: '/admin/events/$eventId/start-round'
      fullPath: '/admin/events/$eventId/start-round'
      preLoaderRoute: typeof AdminEventsEventIdStartRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventId/pairings': {
      id: '/admin/events/$eventId/pairings'
      path: '/admin/events/$eventId/pairings'
      fullPath: '/admin/events/$eventId/pairings'
      preLoaderRoute: typeof AdminEventsEventIdPairingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/event-rounds/$eventRoundId/sub-games': {
      id: '/admin/event-rounds/$eventRoundId/sub-games'
      path: '/admin/event-rounds/$eventRoundId/sub-games'
      fullPath: '/admin/event-rounds/$eventRoundId/sub-games'
      preLoaderRoute: typeof AdminEventRoundsEventRoundIdSubGamesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeRoute: MeRoute,
  ProfileRoute: ProfileRoute,
  AuthConflictRoute: AuthConflictRoute,
  AuthDeclinedRoute: AuthDeclinedRoute,
  InviteTokenRoute: InviteTokenRoute,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminCoursesUploadRoute: AdminCoursesUploadRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  EventsEventIdBetsRoute: EventsEventIdBetsRoute,
  EventsEventIdGalleryRoute: EventsEventIdGalleryRoute,
  EventsEventIdLeaderboardRoute: EventsEventIdLeaderboardRoute,
  EventsEventIdMoneyRoute: EventsEventIdMoneyRoute,
  EventsEventIdScheduleRoute: EventsEventIdScheduleRoute,
  EventsEventIdSettleUpRoute: EventsEventIdSettleUpRoute,
  RoundsRoundIdScoreEntryRoute: RoundsRoundIdScoreEntryRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
  AdminEventRoundsEventRoundIdSubGamesRoute:
    AdminEventRoundsEventRoundIdSubGamesRoute,
  AdminEventsEventIdPairingsRoute: AdminEventsEventIdPairingsRoute,
  AdminEventsEventIdStartRoundRoute: AdminEventsEventIdStartRoundRoute,
  AdminGroupsGroupIdEditRoute: AdminGroupsGroupIdEditRoute,
  AdminRuleSetsIdEditRoute: AdminRuleSetsIdEditRoute,
  EventsEventIdCoursesCourseIdRoute: EventsEventIdCoursesCourseIdRoute,
  AdminEventsEventIdIndexRoute: AdminEventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
