/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDeclinedRouteImport } from './routes/auth.declined'
import { Route as AdminCoursesUploadRouteImport } from './routes/admin.courses.upload'
import { Route as AdminCoursesNewRouteImport } from './routes/admin.courses.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDeclinedRoute = AuthDeclinedRouteImport.update({
  id: '/auth/declined',
  path: '/auth/declined',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesUploadRoute = AdminCoursesUploadRouteImport.update({
  id: '/admin/courses/upload',
  path: '/admin/courses/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesNewRoute = AdminCoursesNewRouteImport.update({
  id: '/admin/courses/new',
  path: '/admin/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/declined': typeof AuthDeclinedRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/upload': typeof AdminCoursesUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/declined': typeof AuthDeclinedRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/upload': typeof AdminCoursesUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/declined': typeof AuthDeclinedRoute
  '/admin/courses/new': typeof AdminCoursesNewRoute
  '/admin/courses/upload': typeof AdminCoursesUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/declined'
    | '/admin/courses/new'
    | '/admin/courses/upload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/declined' | '/admin/courses/new' | '/admin/courses/upload'
  id:
    | '__root__'
    | '/'
    | '/auth/declined'
    | '/admin/courses/new'
    | '/admin/courses/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthDeclinedRoute: typeof AuthDeclinedRoute
  AdminCoursesNewRoute: typeof AdminCoursesNewRoute
  AdminCoursesUploadRoute: typeof AdminCoursesUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/declined': {
      id: '/auth/declined'
      path: '/auth/declined'
      fullPath: '/auth/declined'
      preLoaderRoute: typeof AuthDeclinedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/upload': {
      id: '/admin/courses/upload'
      path: '/admin/courses/upload'
      fullPath: '/admin/courses/upload'
      preLoaderRoute: typeof AdminCoursesUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/new': {
      id: '/admin/courses/new'
      path: '/admin/courses/new'
      fullPath: '/admin/courses/new'
      preLoaderRoute: typeof AdminCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthDeclinedRoute: AuthDeclinedRoute,
  AdminCoursesNewRoute: AdminCoursesNewRoute,
  AdminCoursesUploadRoute: AdminCoursesUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
