/**
 * TypeScript types for Wolf Cup 2025 season fixture data.
 * Generated by packages/engine/scripts/extract-2025-fixtures.py from the Excel source.
 * These are plain data types — no engine imports.
 */

export interface PlayerRoundFixture {
  name: string;
  stableford: number;
  money: number;
  expectedHarveyStableford: number;
  expectedHarveyMoney: number;
}

export interface RoundFixture {
  round: number;
  date: string;
  players: readonly PlayerRoundFixture[];
}

export interface PlayerSeasonStandings {
  name: string;
  roundsPlayed: number;
  roundsDropped: number;
  /** Combined season total: best-10 stableford Harvey + best-10 money Harvey */
  expectedSeasonTotal: number;
}

export interface SeasonStandings {
  players: readonly PlayerSeasonStandings[];
}
